### ISSUE TITLE
bug(smart-camera): picamera crashes

### ISSUE THREAD

**Issue by AlexBtlle** [bobby-home/bobby-home#207]
## What app
- smart camera

## Explain
Camera service turn off and the docker container did not restart.

## Error log
```
2021-04-29 12:45:55	
picamera.exc.PiCameraRuntimeError: Timed out waiting for capture to end
2021-04-29 12:45:55	
    'Timed out waiting for capture to end')
2021-04-29 12:45:55	
  File "/home/camera/.local/lib/python3.7/site-packages/picamera/camera.py", line 1704, in capture_continuous
2021-04-29 12:45:55	
    for _ in camera.capture_continuous(raw_capture, format='jpeg', use_video_port=True):
2021-04-29 12:45:55	
  File "/usr/src/app/camera/pivideostream.py", line 45, in run
2021-04-29 12:45:55	
    stream.run()
2021-04-29 12:45:55	
  File "/usr/src/app/service_manager/run_camera_frame_producer.py", line 89, in run
2021-04-29 12:45:55	
    self._target(*self._args, **self._kwargs)
2021-04-29 12:45:55	
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
2021-04-29 12:45:55	
    self.run()
2021-04-29 12:45:55	
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
```

## Version
bobbyhome/camera:0.4.1

**Comment by mxmaxime** [comment]
Research:
- https://www.raspberrypi.org/forums/viewtopic.php?t=77487 no solution
- https://raspberrypi.stackexchange.com/questions/40126/can-the-gpio-interfere-with-the-picamera-and-cause-an-error no solution @JarJarFlash does not use any gpio.
- https://sourceforge.net/p/raspberry-gpio-python/tickets/94/ according to this issue, it could be related to linux threads. I will try to create/stop a lot of threads to see either the picamera crashes or not.

**Comment by AlexBtlle** [comment]
Got the same error again and the service did not restart, I had to do myself.

Logs:

```
2021-08-27 15:04:26 | picamera.exc.PiCameraRuntimeError: Timed out waiting for capture to end
-- | --
  |   | 2021-08-27 15:04:26 | 'Timed out waiting for capture to end')
  |   | 2021-08-27 15:04:26 | File "/home/camera/.local/lib/python3.7/site-packages/picamera/camera.py", line 1704, in capture_continuous
  |   | 2021-08-27 15:04:26 | for _ in camera.capture_continuous(raw_capture, format='jpeg', use_video_port=True):
  |   | 2021-08-27 15:04:26 | File "/usr/src/app/camera/pivideostream.py", line 45, in run
  |   | 2021-08-27 15:04:26 | stream.run()
  |   | 2021-08-27 15:04:26 | File "/usr/src/app/service_manager/run_camera_frame_producer.py", line 89, in run
  |   | 2021-08-27 15:04:26 | self._target(*self._args, **self._kwargs)
  |   | 2021-08-27 15:04:26 | File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
  |   | 2021-08-27 15:04:26 | self.run()
  |   | 2021-08-27 15:04:26 | File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
  |   | 2021-08-27 15:04:26 | Traceback (most recent call last):
  |   | 2021-08-27 15:04:26 | Process Process-7:
```
